global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "scheduler"

    # Override global settings
    scrape_interval: 5s

    static_configs:
      - targets: ["scheduler:9464"]
